-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\pid_discrete_controller.vhd
-- Created: 2014-07-16 16:48:08
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.001
-- Target subsystem base rate: 0.001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pid_discrete_controller
-- Source Path: pid_discrete_controller
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY pid_discrete_controller IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    real;  -- double
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   real  -- double
        );
END pid_discrete_controller;


ARCHITECTURE rtl OF pid_discrete_controller IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL s_denom_acc_out1                 : real := 0.0;  -- double
  SIGNAL s_state_out1_1                   : real := 0.0;  -- double
  SIGNAL s_denom_gain1                    : real := 0.0;  -- double
  SIGNAL s_nume_gain_b0                   : real := 0.0;  -- double
  SIGNAL s_nume_gain1                     : real := 0.0;  -- double
  SIGNAL s_nume_acc_out1                  : real := 0.0;  -- double

BEGIN
  enb <= clk_enable;

  s_state_out1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      s_state_out1_1 <= 0.0;
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        s_state_out1_1 <= s_denom_acc_out1;
      END IF;
    END IF;
  END PROCESS s_state_out1_process;


  s_denom_gain1 <=  - (s_state_out1_1);

  s_denom_acc_out1 <= In1 - s_denom_gain1;

  s_nume_gain_b0 <= 19.5284 * s_denom_acc_out1;

  s_nume_gain1 <= (-19.3331155) * s_state_out1_1;

  s_nume_acc_out1 <= s_nume_gain_b0 + s_nume_gain1;

  ce_out <= clk_enable;

  Out1 <= s_nume_acc_out1;

END rtl;

