-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\untitled.vhd
-- Created: 2014-07-02 17:03:22
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 0.1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: untitled
-- Source Path: untitled
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY untitled IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    real;  -- double
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   real  -- double
        );
END untitled;


ARCHITECTURE rtl OF untitled IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL s_state_out1                     : real := 0.0;  -- double
  SIGNAL s_state_out2_1                   : real := 0.0;  -- double
  SIGNAL s_denom_gain2                    : real := 0.0;  -- double
  SIGNAL s_denom_gain1                    : real := 0.0;  -- double
  SIGNAL s_denom_acc_out1                 : real := 0.0;  -- double
  SIGNAL s_denom_acc_out2                 : real := 0.0;  -- double
  SIGNAL s_nume_gain1                     : real := 0.0;  -- double
  SIGNAL s_nume_gain2                     : real := 0.0;  -- double
  SIGNAL s_nume_acc_out1                  : real := 0.0;  -- double

BEGIN
  enb <= clk_enable;

  s_state_out2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      s_state_out2_1 <= 0.0;
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        s_state_out2_1 <= s_state_out1;
      END IF;
    END IF;
  END PROCESS s_state_out2_process;


  s_denom_gain2 <= 0.9129 * s_state_out2_1;

  s_denom_gain1 <= (-1.9129) * s_state_out1;

  s_denom_acc_out1 <= In1 - s_denom_gain1;

  s_denom_acc_out2 <= s_denom_acc_out1 - s_denom_gain2;

  s_state_out1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      s_state_out1 <= 0.0;
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        s_state_out1 <= s_denom_acc_out2;
      END IF;
    END IF;
  END PROCESS s_state_out1_1_process;


  s_nume_gain1 <= 0.00044908 * s_state_out1;

  s_nume_gain2 <= 0.00043565 * s_state_out2_1;

  s_nume_acc_out1 <= s_nume_gain1 + s_nume_gain2;

  ce_out <= clk_enable;

  Out1 <= s_nume_acc_out1;

END rtl;

