-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\discrete_plant.vhd
-- Created: 2014-07-16 16:49:11
-- 
-- Generated by MATLAB 8.0 and HDL Coder 3.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.001
-- Target subsystem base rate: 0.001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: discrete_plant
-- Source Path: discrete_plant
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY discrete_plant IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    real;  -- double
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   real  -- double
        );
END discrete_plant;


ARCHITECTURE rtl OF discrete_plant IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL s_state_out1                     : real := 0.0;  -- double
  SIGNAL s_denom_gain1                    : real := 0.0;  -- double
  SIGNAL s_denom_acc_out1                 : real := 0.0;  -- double
  SIGNAL s_nume_gain1                     : real := 0.0;  -- double

BEGIN
  enb <= clk_enable;

  s_denom_gain1 <= (-0.990049833749168) * s_state_out1;

  s_denom_acc_out1 <= In1 - s_denom_gain1;

  s_state_out1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      s_state_out1 <= 0.0;
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        s_state_out1 <= s_denom_acc_out1;
      END IF;
    END IF;
  END PROCESS s_state_out1_1_process;


  s_nume_gain1 <= 0.00099501662508319467 * s_state_out1;

  ce_out <= clk_enable;

  Out1 <= s_nume_gain1;

END rtl;

